# Generated by Django 5.1.3 on 2024-11-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the development tool', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='A short description of the tool', null=True)),
                ('website', models.URLField(help_text='Official website of the tool or documentation URL')),
                ('added_on', models.DateTimeField(auto_now_add=True, help_text='Time when the tool was first added')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Time when the tool data was last updated')),
            ],
        ),
    ]
